### ISSUE TITLE
nothing happens when I run it

### ISSUE THREAD

**Issue by gaizeror** [BonnierNews/saltstack_exporter#1]
Hey,

When i run salt_exporter, nothing happens. 
When i run `netstat -lnp`, I dont see any new port exposed.

What I did is:
1. cloned the repo
2. python setup.py install
3. saltstack_exporter &

nothing happens.
Hope you may help me, if it will work, will be happy to help improving it.

**Comment by carlpett** [comment]
Hi,
Sorry to hear that! Do you get any log output at all? Could you try starting it with `--log-level DEBUG`?
Also, a bit of system information would be useful. What versions of python and saltstack are you running? What Linux distro?

**Comment by gaizeror** [comment]
Thanks for your fast answer.
```
root@vagrant:/# salt-master --versions-report
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-81-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```
I am using python 2.7.

Where is the log file? cant find it. Tried DEBUG but no stdout/stderr

**Comment by carlpett** [comment]
That is very odd. Everything is supposed to go to stdout/stderr, so it must be going wrong very early here. If you start it without the forking (no `&` after `saltstack_exporter`), does it immediately exit, or does it just hang around?

**Comment by gaizeror** [comment]
just hang around

**Comment by carlpett** [comment]
Hm. I don't have access to my development environment at the moment so I have a bit of a hard time testing myself, unfortunately. Could you try to run an python interactive mode? First just see if all the imports in the [main file](https://github.com/BonnierNews/saltstack_exporter/blob/master/saltstack_exporter/exporter.py) actually complete. Or add a generous sprinkling of `print` statements... Just to see where it stops.

**Comment by gaizeror** [comment]
No output to this command if that is what you meant
`python -i /usr/local/bin/saltstack_exporter  --log-level DEBUG`

**Comment by carlpett** [comment]
No, what I meant was far more low-tech :) Just open an interactive python session/REPL with `python`.
Then copy/paste the imports into the terminal and see if that completes (I've seen on some occasions that library imports hang, so that's why I'm suggesting it).

If that completes successfully, I'm afraid the most sophisticated form of troubleshooting is to try editing the `exporter.py` file to add in `print` statements so you can see the progress. We can conclude that you do not reach the start of the web server, since that has [such output just before it](https://github.com/BonnierNews/saltstack_exporter/blob/master/saltstack_exporter/exporter.py#L166).

**Comment by carlpett** [comment]
Oh, another idea: do you have SELinux enabled? Check with `getenforce` if you are not sure.

**Comment by gaizeror** [comment]
well, I dont have SELinux installed at all.
should I install it?

**Comment by carlpett** [comment]
No, it is not a requirement :) It is however a frequent cause of mysterious problems when not configured properly. But let's strike that from the list, then.

**Comment by carlpett** [comment]
It's getting pretty late here - but when you have had the opportunity to try the suggestions in the comment before the SELinux sidetrack, please post the results and I will look at it tomorrow!

**Comment by gaizeror** [comment]
well when i pasted the imports, there were no output

I did:
1. python
2.
```
import argparse
import logging
import threading
import sys
import time
```

**Comment by carlpett** [comment]
@gaizeror I have created a branch which contains a lot of debug output, could you test it? Just check out `troubleshooting/1`.

**Comment by carlpett** [comment]
Closing for lack of response. Please re-open if the issue persists!
